/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	nyctoniddevv1alpha1 "github.com/nidhey27/backup-and-restore/pkg/apis/nyctonid.dev/v1alpha1"
	versioned "github.com/nidhey27/backup-and-restore/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nidhey27/backup-and-restore/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nidhey27/backup-and-restore/pkg/client/listers/nyctonid.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// BackupNRestoreInformer provides access to a shared informer and lister for
// BackupNRestores.
type BackupNRestoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.BackupNRestoreLister
}

type backupNRestoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewBackupNRestoreInformer constructs a new informer for BackupNRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewBackupNRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredBackupNRestoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredBackupNRestoreInformer constructs a new informer for BackupNRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredBackupNRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NyctonidV1alpha1().BackupNRestores(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NyctonidV1alpha1().BackupNRestores(namespace).Watch(context.TODO(), options)
			},
		},
		&nyctoniddevv1alpha1.BackupNRestore{},
		resyncPeriod,
		indexers,
	)
}

func (f *backupNRestoreInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredBackupNRestoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *backupNRestoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nyctoniddevv1alpha1.BackupNRestore{}, f.defaultInformer)
}

func (f *backupNRestoreInformer) Lister() v1alpha1.BackupNRestoreLister {
	return v1alpha1.NewBackupNRestoreLister(f.Informer().GetIndexer())
}
