/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	nyctoniddevv1alpha1 "github.com/nidhey27/respaldo/pkg/apis/nyctonid.dev/v1alpha1"
	versioned "github.com/nidhey27/respaldo/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nidhey27/respaldo/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nidhey27/respaldo/pkg/client/listers/nyctonid.dev/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// RespaldoInformer provides access to a shared informer and lister for
// Respaldos.
type RespaldoInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.RespaldoLister
}

type respaldoInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewRespaldoInformer constructs a new informer for Respaldo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewRespaldoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredRespaldoInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredRespaldoInformer constructs a new informer for Respaldo type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredRespaldoInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NyctonidV1alpha1().Respaldos(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.NyctonidV1alpha1().Respaldos(namespace).Watch(context.TODO(), options)
			},
		},
		&nyctoniddevv1alpha1.Respaldo{},
		resyncPeriod,
		indexers,
	)
}

func (f *respaldoInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredRespaldoInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *respaldoInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&nyctoniddevv1alpha1.Respaldo{}, f.defaultInformer)
}

func (f *respaldoInformer) Lister() v1alpha1.RespaldoLister {
	return v1alpha1.NewRespaldoLister(f.Informer().GetIndexer())
}
