/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1alpha1 "github.com/nidhey27/backup-and-restore/pkg/apis/nyctonid.dev/v1alpha1"
	nyctoniddevv1alpha1 "github.com/nidhey27/backup-and-restore/pkg/client/applyconfiguration/nyctonid.dev/v1alpha1"
	scheme "github.com/nidhey27/backup-and-restore/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BackupNRestoresGetter has a method to return a BackupNRestoreInterface.
// A group's client should implement this interface.
type BackupNRestoresGetter interface {
	BackupNRestores(namespace string) BackupNRestoreInterface
}

// BackupNRestoreInterface has methods to work with BackupNRestore resources.
type BackupNRestoreInterface interface {
	Create(ctx context.Context, backupNRestore *v1alpha1.BackupNRestore, opts v1.CreateOptions) (*v1alpha1.BackupNRestore, error)
	Update(ctx context.Context, backupNRestore *v1alpha1.BackupNRestore, opts v1.UpdateOptions) (*v1alpha1.BackupNRestore, error)
	UpdateStatus(ctx context.Context, backupNRestore *v1alpha1.BackupNRestore, opts v1.UpdateOptions) (*v1alpha1.BackupNRestore, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.BackupNRestore, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.BackupNRestoreList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BackupNRestore, err error)
	Apply(ctx context.Context, backupNRestore *nyctoniddevv1alpha1.BackupNRestoreApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BackupNRestore, err error)
	ApplyStatus(ctx context.Context, backupNRestore *nyctoniddevv1alpha1.BackupNRestoreApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BackupNRestore, err error)
	BackupNRestoreExpansion
}

// backupNRestores implements BackupNRestoreInterface
type backupNRestores struct {
	client rest.Interface
	ns     string
}

// newBackupNRestores returns a BackupNRestores
func newBackupNRestores(c *NyctonidV1alpha1Client, namespace string) *backupNRestores {
	return &backupNRestores{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the backupNRestore, and returns the corresponding backupNRestore object, and an error if there is any.
func (c *backupNRestores) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.BackupNRestore, err error) {
	result = &v1alpha1.BackupNRestore{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupnrestores").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BackupNRestores that match those selectors.
func (c *backupNRestores) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.BackupNRestoreList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BackupNRestoreList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("backupnrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested backupNRestores.
func (c *backupNRestores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("backupnrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a backupNRestore and creates it.  Returns the server's representation of the backupNRestore, and an error, if there is any.
func (c *backupNRestores) Create(ctx context.Context, backupNRestore *v1alpha1.BackupNRestore, opts v1.CreateOptions) (result *v1alpha1.BackupNRestore, err error) {
	result = &v1alpha1.BackupNRestore{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("backupnrestores").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backupNRestore).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a backupNRestore and updates it. Returns the server's representation of the backupNRestore, and an error, if there is any.
func (c *backupNRestores) Update(ctx context.Context, backupNRestore *v1alpha1.BackupNRestore, opts v1.UpdateOptions) (result *v1alpha1.BackupNRestore, err error) {
	result = &v1alpha1.BackupNRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backupnrestores").
		Name(backupNRestore.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backupNRestore).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *backupNRestores) UpdateStatus(ctx context.Context, backupNRestore *v1alpha1.BackupNRestore, opts v1.UpdateOptions) (result *v1alpha1.BackupNRestore, err error) {
	result = &v1alpha1.BackupNRestore{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("backupnrestores").
		Name(backupNRestore.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(backupNRestore).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the backupNRestore and deletes it. Returns an error if one occurs.
func (c *backupNRestores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupnrestores").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *backupNRestores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("backupnrestores").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched backupNRestore.
func (c *backupNRestores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.BackupNRestore, err error) {
	result = &v1alpha1.BackupNRestore{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("backupnrestores").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied backupNRestore.
func (c *backupNRestores) Apply(ctx context.Context, backupNRestore *nyctoniddevv1alpha1.BackupNRestoreApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BackupNRestore, err error) {
	if backupNRestore == nil {
		return nil, fmt.Errorf("backupNRestore provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(backupNRestore)
	if err != nil {
		return nil, err
	}
	name := backupNRestore.Name
	if name == nil {
		return nil, fmt.Errorf("backupNRestore.Name must be provided to Apply")
	}
	result = &v1alpha1.BackupNRestore{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("backupnrestores").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *backupNRestores) ApplyStatus(ctx context.Context, backupNRestore *nyctoniddevv1alpha1.BackupNRestoreApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.BackupNRestore, err error) {
	if backupNRestore == nil {
		return nil, fmt.Errorf("backupNRestore provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(backupNRestore)
	if err != nil {
		return nil, err
	}

	name := backupNRestore.Name
	if name == nil {
		return nil, fmt.Errorf("backupNRestore.Name must be provided to Apply")
	}

	result = &v1alpha1.BackupNRestore{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("backupnrestores").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
